"""Add Canvas-style time tracking fields to subtasks

Revision ID: 057d43985215
Revises: 20240605_onboarded
Create Date: 2025-07-18 19:37:22.044088

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '057d43985215'
down_revision = '20240605_onboarded'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_courses_goal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subtask_engagement_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subtask_engagement_end', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('subtask_total_active_minutes', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('subtask_last_interaction', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users_courses_goal', schema=None) as batch_op:
        batch_op.drop_column('subtask_last_interaction')
        batch_op.drop_column('subtask_total_active_minutes')
        batch_op.drop_column('subtask_engagement_end')
        batch_op.drop_column('subtask_engagement_start')
    # ### end Alembic commands ###